# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Giaodien.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_show_img = QtWidgets.QLabel(self.centralwidget)
        self.lb_show_img.setGeometry(QtCore.QRect(40, 100, 598, 598))
        self.lb_show_img.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_show_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb_show_img.setText("")
        self.lb_show_img.setObjectName("lb_show_img")
        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(160, 50, 93, 28))
        self.btn_predict.setObjectName("btn_predict")
        self.btn_open_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_img.setGeometry(QtCore.QRect(40, 50, 93, 28))
        self.btn_open_img.setObjectName("btn_open_img")
        self.Connection_Camera_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.Connection_Camera_2.setGeometry(QtCore.QRect(780, 320, 391, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Connection_Camera_2.setFont(font)
        self.Connection_Camera_2.setObjectName("Connection_Camera_2")
        self.lb_result = QtWidgets.QLabel(self.Connection_Camera_2)
        self.lb_result.setGeometry(QtCore.QRect(90, 50, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_result.setFont(font)
        self.lb_result.setText("")
        self.lb_result.setObjectName("lb_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1187, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_predict.setText(_translate("MainWindow", "Run"))
        self.btn_open_img.setText(_translate("MainWindow", "Open"))
        self.Connection_Camera_2.setTitle(_translate("MainWindow", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
